### ISSUE TITLE
Added analytes cannot be simulated

### ISSUE THREAD

**Issue by jkelowitt** [dalevens/OpenTitration#11]
1. Perform all steps necessary to perform simulation
2. Click "Known" analyte
3. Add a new analyte
4. Set Known Analyte to the new analyte.
5. Click simulate
6. Observe error. 

![image](https://user-images.githubusercontent.com/58435724/111556436-35856480-8750-11eb-992a-4ec883fcb612.png)

**Comment by dalevens** [comment]
hmmm, this one is weird I do not get this error. Is this a di or triprotic acid where you get this error?
