### ISSUE TITLE
Clicking, "Known" Will clear the contents of the titrant concentration.

### ISSUE THREAD

**Issue by jkelowitt** [dalevens/OpenTitration#17]
Version: 2.0.0
Build: 20210402

Steps:
- Open Program
- Enter a number into the Titrant concentration
- Click "Known"
- Observe that what was entered was cleared. 

I would expect that the number I type in should remain in the box, and would be used as the titrant concentration.

**Comment by dalevens** [comment]
Ah, I initially designed it that way, but your right I'll remove that!

**Comment by dalevens** [comment]
This has been cleared, however it will still remove the mass and volume in the titrant form.
