### ISSUE TITLE
Pressing the tab key navigates the input boxes in an unexpected order. 

### ISSUE THREAD

**Issue by jkelowitt** [dalevens/OpenTitration#18]
Version: 2.0.0
Build: 20210402

Steps:
- Open the program
- Click on the formula input box
- Press tab (Should change cursor location to the (g/mol) input box)
- Press tab again (Cursor moves to an unknown location)
- Pressing table more times results in the cursor moving to different input locations with no discernible pattern. 

I would expect the navigation to proceed:
- **Titrant**
  - Formula
  - (g/mol)
  - Mass
  - Volume
  - Concentration
 
 - Molar Ratio

- **Analyte** 
  - Volume
  - Dilution Factor
  - Equivalence
  - Concentration

- **Results**
  - pKa
  - Known Acid

**Comment by dalevens** [comment]
Tab order has been changed to logical flow. This has also been updated in the settings as well. Good catch! I rarely use tab controls to navigate through something.
