### ISSUE TITLE
Simulator does not resimulate correctly when changing concentration.

### ISSUE THREAD

**Issue by jkelowitt** [dalevens/OpenTitration#2]
First Simulation:
![Second Sim](https://i.imgur.com/tMmzB11.png)

Second simulation:
![Second Sim](https://i.imgur.com/3clGmuI.png)

The second simulation should have a smaller maximum due to the decreased concentration.

**Comment by jkelowitt** [comment]
Wrong branch

**Comment by jkelowitt** [comment]
Analyze must be clicked before clicking simulate to get the simulation to update.

**Comment by dalevens** [comment]
Previously as you mentioned the concentration had to be clicked to update the known concentration. Now if the analysis has been completed and a known concentration  has been added (known concentration checkbox) the calculated concentration of the unknown will automatically be updated. This only happens specifically with a change of concentration of the titrant. The figures will not be updated if someone changes the molar ratio, analyte volume or dilution factor. Please let me know if I should do this for everything!
