### ISSUE TITLE
Analyzing with small concentrations results in a concentration of Zero for simulation. 

### ISSUE THREAD

**Issue by jkelowitt** [dalevens/OpenTitration#3]
![](https://i.imgur.com/e0eG34T.png)

The concentration of the analyte isn't zero, and this is shown when opening the concentration drop down. This value is ~9.999E-6:
![](https://i.imgur.com/6jY4iLo.png)

**Comment by dalevens** [comment]
This issue has been corrected! Small values are now converted to scientific format, and pass properly to the python script.
