### ISSUE TITLE
Advanced PDF formatting ideas

### ISSUE THREAD

**Issue by jkelowitt** [dalevens/OpenTitration#7]
Allow the user to change the color of the lines plotted in the graph. 
Allow the user to specify whether lines or points should be plotted. 
Allow the user to title axes or the plot itself. Etc.
Allow the user to export vector graphics of the graph.

**Comment by dalevens** [comment]
With the exception of the titles and vector graphics this section has been completed. The user can still export the graph independently as a .png file as an option under export.
